### PR TITLE
added programmatic api

### PR DESCRIPTION
**Pull request by tcql**
So you can do something like:

```
xyz = require('geojson-xyz');

xyz('islands', function(res, file) { 
  res.on('end', function () {console.log('done'); })
    .pipe(fs.createWriteStream(file.original)); 
});
```

potentially neat for node automation scripts?

### CODE REVIEW

**Comment by tmcw** [comment]
:+1: awesome: if we're going to present a user-level API, thoughts on making the function take `(err, geojsonObject)` instead of a response stream? The expectation to concat the stream and JSON.parse might lead to a bit of repeated boilerplate for end-users and since we're planning on only permitting mid-size datasets there shouldn't be a strong perf reason for streams.

**Comment by tcql** [comment]
@tmcw yea, makes sense to me. I kept the stream so I could easily drop in the API as a replacement for the manual HTTP calls in the xyz bin script, but that could be switched to non-streaming as well.

**Comment by tcql** [comment]
@tmcw So, what I've got now is a callback that takes `(err, result)`. Result looks like this: 

`{file: 'the source filename', geojson: {/* the result geojson, parsed */}`

Reworked everything in the bin script to use this (also fixed a woops I did regarding the `--` parameter

**Comment by tmcw** [comment]
:+1: awesome. will merge in a sec.

**Comment by tmcw** [comment]
Merged in 0338dd6aaa601937aa633d1da16730ed7522ae2b thx!

**Pull request closed without merging**
